// Default pricing items for new pricing lists - Based on Price Code D template
export const DEFAULT_PRICING_ITEMS = {
  digital_packages: [
    { id: `digital-${Date.now()}-1`, name: '1 Digital File', price: 65.00, cost: 2.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-2`, name: '2 Digital Files', price: 80.00, cost: 4.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-3`, name: '3 Digitals Get One Free', price: 100.00, cost: 6.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-4`, name: '4 Digitals Get One Free', price: 120.00, cost: 8.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-5`, name: '5 Digitals Get One Free', price: 140.00, cost: 10.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-6`, name: '6 Digitals Get One Free', price: 160.00, cost: 12.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-7`, name: '7 Digitals Get One Free', price: 180.00, cost: 14.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-8`, name: '8 Digitals Get One Free', price: 200.00, cost: 16.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-9`, name: '9 Digitals Get One Free', price: 220.00, cost: 18.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-10`, name: '10 Digitals Get One Free', price: 240.00, cost: 20.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-11`, name: '11 Digitals Get One Free', price: 260.00, cost: 22.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-12`, name: '12 Digitals Get One Free', price: 280.00, cost: 24.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-13`, name: '13 Digitals Get One Free', price: 300.00, cost: 26.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-14`, name: '14 Digitals Get One Free', price: 320.00, cost: 28.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-15`, name: '15 Digitals Get One Free', price: 340.00, cost: 30.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-16`, name: '16 Digitals Get One Free', price: 360.00, cost: 32.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-17`, name: '17 Digitals Get One Free', price: 380.00, cost: 34.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-18`, name: '18 Digitals Get One Free', price: 400.00, cost: 36.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-19`, name: '19 Digitals Get One Free', price: 420.00, cost: 38.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-20`, name: '20 Digitals Get One Free', price: 440.00, cost: 40.00, type: 'digital-package' as const },
    { id: `digital-${Date.now()}-21`, name: '21 Digitals Get One Free', price: 460.00, cost: 42.00, type: 'digital-package' as const },
  ],
  packages: [
    // Multi-Pose
    { id: `pkg-multi-${Date.now()}-1`, name: 'Package A', price: 90.00, cost: 12.00, type: 'multi-pose' as const, numberOfPoses: 3, sheetSizes: [{ size: '8x10', qty: '1' }, { size: '5x7', qty: '2' }, { size: '3.5x5', qty: '4' }, { size: 'Wallets', qty: '8' }] },
    { id: `pkg-multi-${Date.now()}-2`, name: 'Package B', price: 80.00, cost: 10.00, type: 'multi-pose' as const, numberOfPoses: 2, sheetSizes: [{ size: '8x10', qty: '1' }, { size: '5x7', qty: '4' }, { size: '3.5x5', qty: '4' }, { size: 'Wallets', qty: '8' }] },
    { id: `pkg-multi-${Date.now()}-3`, name: 'Package C', price: 70.00, cost: 8.00, type: 'multi-pose' as const, numberOfPoses: 2, sheetSizes: [{ size: '8x10', qty: '1' }, { size: '5x7', qty: '2' }, { size: '3.5x5', qty: '4' }, { size: 'Wallets', qty: '8' }] },
    // Single-Pose
    { id: `pkg-single-${Date.now()}-1`, name: 'Package D', price: 60.00, cost: 6.00, type: 'single-pose' as const, sheetSizes: [{ size: '8x10', qty: '1' }, { size: '5x7', qty: '2' }, { size: '3.5x5', qty: '8' }, { size: 'Wallets', qty: '16' }] },
    { id: `pkg-single-${Date.now()}-2`, name: 'Package E', price: 50.00, cost: 4.00, type: 'single-pose' as const, sheetSizes: [{ size: '8x10', qty: '1' }, { size: '5x7', qty: '2' }, { size: '3.5x5', qty: '4' }, { size: 'Wallets', qty: '8' }] },
    { id: `pkg-single-${Date.now()}-3`, name: 'Package F', price: 40.00, cost: 3.00, type: 'single-pose' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '2' }, { size: '3.5x5', qty: '4' }, { size: 'Wallets', qty: '8' }] },
    { id: `pkg-single-${Date.now()}-4`, name: 'Package G', price: 30.00, cost: 2.00, type: 'single-pose' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '2' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '8' }] },
  ],
  build_your_own: [
    { id: `byo-${Date.now()}-1`, name: '2 Sheets', price: 40.00, cost: 2.00, type: 'build-your-own' as const, sheetSizes: [{ size: '8x10', qty: '' }, { size: '5x7', qty: '' }, { size: '3.5x5', qty: '' }, { size: 'Wallets', qty: '' }] },
    { id: `byo-${Date.now()}-2`, name: '3 Sheets', price: 50.00, cost: 3.00, type: 'build-your-own' as const, sheetSizes: [{ size: '8x10', qty: '' }, { size: '5x7', qty: '' }, { size: '3.5x5', qty: '' }, { size: 'Wallets', qty: '' }] },
    { id: `byo-${Date.now()}-3`, name: '4 Sheets', price: 60.00, cost: 4.00, type: 'build-your-own' as const, sheetSizes: [{ size: '8x10', qty: '' }, { size: '5x7', qty: '' }, { size: '3.5x5', qty: '' }, { size: 'Wallets', qty: '' }] },
    { id: `byo-${Date.now()}-4`, name: '5 Sheets', price: 70.00, cost: 5.00, type: 'build-your-own' as const, sheetSizes: [{ size: '8x10', qty: '' }, { size: '5x7', qty: '' }, { size: '3.5x5', qty: '' }, { size: 'Wallets', qty: '' }] },
    { id: `byo-${Date.now()}-5`, name: '6 Sheets', price: 80.00, cost: 6.00, type: 'build-your-own' as const, sheetSizes: [{ size: '8x10', qty: '' }, { size: '5x7', qty: '' }, { size: '3.5x5', qty: '' }, { size: 'Wallets', qty: '' }] },
    { id: `byo-${Date.now()}-6`, name: '8 Sheets', price: 90.00, cost: 8.00, type: 'build-your-own' as const, sheetSizes: [{ size: '8x10', qty: '' }, { size: '5x7', qty: '' }, { size: '3.5x5', qty: '' }, { size: 'Wallets', qty: '' }] },
    { id: `byo-${Date.now()}-7`, name: '10 Sheets', price: 100.00, cost: 10.00, type: 'build-your-own' as const, sheetSizes: [{ size: '8x10', qty: '' }, { size: '5x7', qty: '' }, { size: '3.5x5', qty: '' }, { size: 'Wallets', qty: '' }] },
    { id: `byo-${Date.now()}-8`, name: '12 Sheets', price: 110.00, cost: 12.00, type: 'build-your-own' as const, sheetSizes: [{ size: '8x10', qty: '' }, { size: '5x7', qty: '' }, { size: '3.5x5', qty: '' }, { size: 'Wallets', qty: '' }] },
  ],
  ala_carte: [
    { id: `ala-${Date.now()}-1`, name: 'H1', price: 25.00, cost: 1.00, type: 'ala-carte' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `ala-${Date.now()}-2`, name: 'H2', price: 25.00, cost: 1.00, type: 'ala-carte' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `ala-${Date.now()}-3`, name: 'H3', price: 25.00, cost: 1.00, type: 'ala-carte' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `ala-${Date.now()}-4`, name: 'H4', price: 25.00, cost: 1.00, type: 'ala-carte' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `ala-${Date.now()}-5`, name: 'H5', price: 25.00, cost: 1.00, type: 'ala-carte' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `ala-${Date.now()}-6`, name: 'H8', price: 25.00, cost: 1.00, type: 'ala-carte' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `ala-${Date.now()}-7`, name: 'Single 5x7', price: 15.00, cost: 1.00, type: 'ala-carte' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `ala-${Date.now()}-8`, name: '(4) Wallets', price: 15.00, cost: 1.00, type: 'ala-carte' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `ala-${Date.now()}-9`, name: '(2) 3.5x5', price: 15.00, cost: 1.00, type: 'ala-carte' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `ala-${Date.now()}-10`, name: '5x7 Group', price: 15.00, cost: 1.00, type: 'ala-carte' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `ala-${Date.now()}-11`, name: '8x10 Group', price: 25.00, cost: 1.00, type: 'ala-carte' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
  ],
  wall_portraits: [
    { id: `wall-${Date.now()}-1`, name: '10x13 Print', price: 40.00, cost: 8.00, type: 'wall-portrait' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `wall-${Date.now()}-2`, name: '11x14 Print', price: 50.00, cost: 9.00, type: 'wall-portrait' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `wall-${Date.now()}-3`, name: '16x20 Print', price: 60.00, cost: 15.00, type: 'wall-portrait' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `wall-${Date.now()}-4`, name: '8x10 Canvas', price: 125.00, cost: 60.00, type: 'wall-portrait' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `wall-${Date.now()}-5`, name: '11x14 Canvas', price: 250.00, cost: 70.00, type: 'wall-portrait' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `wall-${Date.now()}-6`, name: '16x20 Canvas', price: 375.00, cost: 95.00, type: 'wall-portrait' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `wall-${Date.now()}-7`, name: '24x30 Canvas', price: 500.00, cost: 150.00, type: 'wall-portrait' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
  ],
  specialty_items: [
    { id: `spec-${Date.now()}-1`, name: '(2) Wallet Magnets', price: 18.00, cost: 1.00, type: 'specialty' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `spec-${Date.now()}-2`, name: 'Photo Keychain', price: 22.00, cost: 5.00, type: 'specialty' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
    { id: `spec-${Date.now()}-3`, name: '15oz Photo Mug', price: 29.99, cost: 7.00, type: 'specialty' as const, sheetSizes: [{ size: '8x10', qty: '0' }, { size: '5x7', qty: '0' }, { size: '3.5x5', qty: '0' }, { size: 'Wallets', qty: '0' }] },
  ],
};
